# Site settings
title: "ğŸ lang"
description: "The official website of the ğŸ  programming language"
owner: "Kurtis Rainbolt-Greene"
github: "http://github.com/beelang/beelang.github.io"
logo: "http://github.com/beelang.png"
analytics: UA-18715035-11
profiles:
  -
    name: "Twitter"
    url: "http://twitter.com/beelang"
  -
    name: "Github"
    url: "http://github.com/beelang"
links:
  -
    name: "About"
    url: "/about"
  -
    name: "ABNF"
    url: "/abnf"

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: /:title/
exclude:
  - Gemfile
  - LICENSE
  - README.md
  - CNAME
  - .ruby-gemset
  - .ruby-version
  - .gitignore
  - _mdwriter.cson
  - _sass
